sudo: required
services: 
    - docker

before_install:
    - docker build -t katja1909/docker-react -f Dockerfile.dev .

script:
    - docker run katja1909/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    enc: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-474934949302"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY" 
